version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    #      volumes:
    #        - /etc/localtime:/etc/localtime
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.30.108
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # topicName:PartitionCount:ReplicationFactor
      KAFKA_CREATE_TOPICS: sync_topic:1:1, zi_topic:1:1, exception_topic:1:1, celery_topic:1:1
  kafka-manager:
    image: sheepkiller/kafka-manager
    environment:
      ZK_HOSTS: 192.168.30.108
    ports:
      - "9000:9000"
  nginx:
    container_name: nginx
    image: nginx:1.12
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - catalyst-api
    restart: always
  catalyst-api:
    container_name: catalyst-api
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./log/:/usr/local/go/src/catalyst.Go/log
    links:
      - zookeeper
      - kafka
    command: supervisord -n
    environment:
      - PORT=8080
      - KAFKA_ADDRESS=192.168.30.108
      - LOG_FILE_NAME=catalyst-api
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    restart: always

networks:
  dev-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.5.254